### ISSUE TITLE
Error in hierarchy.xml for DynamicSpotter

### ISSUE THREAD

**Issue by tormoseng** [CloudScale-Project/Environment#3]
Running both the OLB and StaticSpotter patterns gives an error in the hierarchy.xml file. According to Jure an "uniqueId" field is missing. But in the hierarchy.xml file for the StaticSpotter-pattern a lot more is missing.

**Comment by snowball77** [comment]
The static spotter does not use a hierachy but a catalogue? I am not sure whether I understand the issue description correctly. Also what did you do to reproduce the issue?

**Comment by tormoseng** [comment]
OK. My mistake. Let's try again:
- I set up the DynamicSpotter in CSE 3.2 as I do in the stand-alone version
- Choosing OLB as pattern gives me an error in the hierarchy.xml due to a missing uniqueId under root.
- Trying the StaticSpotterSynchronizedMethodDetectionController instead gives me also an error in the hierarchy.xml file (as reported by the CSE). The xml is attached.
  [hierarchy.pdf](https://github.com/CloudScale-Project/Environment/files/42809/hierarchy.pdf)

**Comment by snowball77** [comment]
Ah, ok, now I understand. You try to use the integration adapter between static spotter and dynamic spotter. This is very experimental so far, but an empty hierachy is definitly wrong. It works in a way where you first run static spotter, export all anti pattern candidates and then import them into the dynamic spotter adapter. I guess, there is no documentation of this procedure yet as it exists only since roughly one week and is still under test in the standalone versions.

**Comment by tormoseng** [comment]
That fresh! Good. We can put my third point on hold so far. @jurepolutnik : The issue about the OLB is still open.

**Comment by jurepolutnik** [comment]
@tormoseng I will see what it can be done... probably fix on DS will be needed.

**Comment by snowball77** [comment]
With the hierachy.xml in the git repository the DS works fine here in standalone. It has to be an integration issue.

**Comment by jurepolutnik** [comment]
probably you are right... i have some idea where to look for it.

**Comment by jurepolutnik** [comment]
Fixed.
